RAILS/initial/config/routes.rb
Rails.application.routes.draw do
  root "student#list"
  get "search", to: "search#index"

  devise_for :users
  resources :posts do
    resources :comments
  end

  get "home", controller: "home", action: "index", as: "home" # Primeira forma de criar um controller
  get "home-2", to: "home2#index" # Segunda forma de criar um controller
  get "estudantes", to: "student#list", as: "studies"
end

RAILS/initial/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  has_rich_text :body
end

RAILS/initial/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user

  def self.ransackable_attributes(auth_object = nil)
    %w[title body] # Lista de atributos permitidos para pesquisa
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

RAILS/initial/app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

RAILS/initial/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_query
  allow_browser versions: :modern

  def set_query
    @query = Post.ransack(params[:q])
  end
end

RAILS/initial/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @comment = @post.comments.create(comments_params)
    @comment.user = current_user

    if @comment.save
      flash[:notice] = "Comentário criado com sucesso"

      # redirect_to post_path(@post)
      redirect_to @post
    else
      flash[:alert] = "Erro ao criar comentario no post #{@post.id}"

      redirect_to post_path(@post)
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

  def update
    @comment = @post.comments.find(params[:id])

    respond_to do |format|
      if @comment.update(comments_params)
        format.html { redirect_to post_url(@post), notice: "Comentário atualizado com sucesso" }
      else
        format.html { redirect_to post_url(@post, notice: "Erro ao atualizar comentário") }
      end
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comments_params
    params.require(:comment).permit(:body)
  end
end

RAILS/initial/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # @message = "Mensagem de boas vindas"

    # render html: "<h2>Olá, mundo #{@message}</h2>".html_safe

    @author = "Matheus"
    @posts = [
      { title: "Rails", body: "Aprendendo Rails" },
      { title: "Laravel", body: "Aprendendo Laravel" },
      { title: "Django", body: "Aprendendo Django" },
    ]
  end
end

RAILS/initial/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(view: @post.view += 1)
    @comments = @post.comments.order(created_at: :desc)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.expect(post: [ :title, :body ])
    end
end

RAILS/initial/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = Post.ransack(params[:q])
    @posts = @query.result(distinct: true)
    puts @post.inspect
  end
end

RAILS/initial/app/controllers/student_controller.rb
class StudentController < ApplicationController
  def list
    @students = [
      { :name => "Matheus", :age => 19, :description => "Lorem ipsum dolor sit amet dallas" },
      { :name => "Matheus2", :age => 19, :description => "Lorem ipsum dolor sit amet dallas" },
      { :name => "Matheus3", :age => 19, :description => "Lorem ipsum dolor sit amet dallas" },
      { :name => "Matheus4", :age => 19, :description => "Lorem ipsum dolor sit amet dallas" },
      { :name => "Matheus5", :age => 19, :description => "Lorem ipsum dolor sit amet dallas" },
    ]
  end
end

RAILS/initial/app/helpers/comments_helper.rb
module CommentsHelper
end

RAILS/initial/app/helpers/posts_helper.rb
module PostsHelper
end

RAILS/initial/app/helpers/search_helper.rb
module SearchHelper
end

RAILS/initial/app/helpers/student_helper.rb
module StudentHelper
end

RAILS/initial/app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

RAILS/initial/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <% # Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <% #= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
    <% # Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flash" %>

    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

RAILS/initial/app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.textarea :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

RAILS/initial/app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <p><%= pluralize(post.view, 'view') %></p>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

RAILS/initial/app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

RAILS/initial/app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

RAILS/initial/app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

RAILS/initial/app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete, data: {turbo_confirm: "Tem certeza que deseja excluir?"} %>
</div>

<%= render "comments/form", post: @post, comment: @post.comments.build, submit_label: "Reply" %>
<% @comments.each do |comment| %>
  <%= render "comments/comment", post: @post, comment: comment %>
<% end %>

RAILS/initial/app/views/search/_form.html.erb
<%= search_form_for @query, url: search_path, method: :get, class: "d-flex" do |f| %>
    <%= f.search_field :title_or_body_cont, placeholder: "Search", class: "form-control me-2" %>

    <%= f.submit :search, class: "btn btn-outline-success" %>
<% end %>

RAILS/initial/app/views/search/index.html.erb
<h1 class="text-center">
    <%= pluralize(@posts.count, "result") %>
</h1>

<%= render "search/form" %>

<div class="container">
    <table class="table  table-striped">
        <thead>
            <tr>
                <th><%= sort_link(@query, :title, "Title", default_order: :asc) %></th>
                <th><%= sort_link(@query, :body, "Content") %></th>
            </tr>
        </thead>
        <tbody>
            <% @posts.each do |post| %>
            <tr>
                <td><%= link_to post.title, post %></td>
                <td><%= post.body.truncate_words(25) %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>